### ISSUE TITLE
initService throws TypeError: workspaceService.acquireInstantiationService is not a function

### ISSUE THREAD

**Issue by rubenfiszel** [TypeFox/monaco-languageclient#547] opened 2023-10-07 09:34 UTC
I'm upgrading from 6.0.0 to latest

I migrated to use the new initServices with all the required extension but initServices always throw:

```Uncaught (in promise) TypeError: workspaceService.acquireInstantiationService is not a function```

**Comment by rubenfiszel** [comment] 2023-10-07 09:37
Those are the versions that I use: 

https://github.com/windmill-labs/windmill/pull/2401/files#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655

and my code changes to the editor: https://github.com/windmill-labs/windmill/pull/2401/files#diff-6c66cfa8f98870ad45bef9f1a81a9e5e745c2a044eb9406cb47a97304ce2e45e

**Comment by CGNonofr** [comment] 2023-10-07 18:11
It happens when the configuration service override is imported but the returned services are not used

One way for it to happens is to create an editor before calling `initServices`

**Comment by kaisalmen** [comment] 2023-11-09 07:55
@rubenfiszel I will close this. If I am an error we can re-open or you open up a follow-up discussion or issue.

**Closed by kaisalmen** 2023-11-09 07:55 UTC

**Comment by todwang** [comment] 2024-03-01 11:05
When I use version 7.3.0, I encounter the same error.

> TypeError: workspaceService.acquireInstantiationService is not a function

code:
`
import configurationService from "@codingame/monaco-vscode-configuration-service-override"
import keybindingsService from "@codingame/monaco-vscode-keybindings-service-override"
import modelService from '@codingame/monaco-vscode-model-service-override'

await initServices({
    ...modelService(),
    ...configurationService(vscode.Uri.file('/workspace')),
    ...keybindingsService()
});
`

**Comment by Lemour-sudo** [comment] 2024-03-26 13:09
@todwang did you manage to get around the problem?

**Comment by Dams591** [comment] 2024-07-01 15:23
Getting the same issue, any idea ?

**Comment by kaisalmen** [comment] 2024-07-02 06:59
Hi @Dams591 are you getting the same issue with the current version of the lib? Can you share a reproducible example / repo? Thank you.

**Comment by saeedvaziry** [comment] 2024-07-14 14:26
Same issue here

**Comment by kaisalmen** [comment] 2024-07-15 06:58
Hi @saeedvaziry do you see the same error message? Can you share a reproducible example / repo? Thank you.

**Comment by kaisalmen** [comment] 2024-07-15 11:58
@saeedvaziry have you tried adding:
```js
import getConfigurationServiceOverride from '@codingame/monaco-vscode-configuration-service-override';
```
or removing/commenting the `workspaceConfig`. 

If you look at bare [monaco-languageclient example](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/bare/client.ts)  it only initializes theme and textmate, because it requires it for the json highlighting instructions being loaded, but apart from it nothing else.

**Comment by saeedvaziry** [comment] 2024-07-15 16:16
@kaisalmen the error goes away but still it doesn't work as expected.

Maybe you can help me figure out what I am doing wrong here.

In the version below which is a copy from the python example of the repo, the editor works fine:

```
wrapper = new MonacoEditorLanguageClientWrapper()
if (!wrapper.isStarted()) {
    await wrapper.dispose()
    await wrapper.init({
        languageClientConfig: {
            languageId: 'php',
            name: 'PHP Language Server',
            options: {
                $type: 'WebSocketUrl',
                url: 'ws://127.0.0.1:8080',
            },
            clientOptions: {
                documentSelector: ['php'],
                workspaceFolder: {
                    index: 0,
                    name: 'workspace-' + tab.value.name,
                    uri: vscode.Uri.parse(`${props.path}`),
                },
            },
        },
        wrapperConfig: {
            editorAppConfig: {
                $type: 'extended',
                codeResources: {
                    main: {
                        text: props.value,
                        // uri: vscode.Uri.parse(
                        //     `${props.path}/hello.php`
                        // ),
                        fileExt: 'php',
                    },
                },
                userConfiguration: {
                    json: JSON.stringify({
                        'workbench.colorTheme':
                            'Default Dark Modern',
                    }),
                },
                editorOptions: {
                    readOnly: props.readonly,
                    fontSize:
                        settingsStore.settings.editor.fontSize,
                    minimap: {
                        enabled: false,
                    },
                    wordWrap:
                        settingsStore.settings.editor.wordWrap,
                    theme: settingsStore.settings.theme,
                    stickyScroll: {
                        enabled: false,
                    },
                    automaticLayout: true,
                    glyphMargin: false,
                    scrollBeyondLastLine: false,
                    lightbulb: { enabled: false },
                    wordBasedSuggestions: 'off',
                    suggestOnTriggerCharacters: true,
                    quickSuggestions: {
                        other: true,
                        comments: true,
                        strings: true,
                    },
                    parameterHints: {
                        enabled: true,
                    },
                },
                useDiffEditor: false,
            },
        },
        loggerConfig: {
            enabled: true,
            debugEnabled: true,
        },
    })
}

await wrapper.start(editorContainer.value)
```

here is a video:

![CleanShot 2024-07-15 at 18 14 48](https://github.com/user-attachments/assets/2f7c8960-19d2-414a-aea7-eb9f25ec16bf)

But I am trying to make it work with the code below which I have more control over the editor:

```
useWorkerFactory({
    ignoreMapping: true,
    workerLoaders: {
        editorWorkerService: () =>
            new Worker(
                new URL(
                    'monaco-editor/esm/vs/editor/editor.worker.js',
                    import.meta.url
                ),
                { type: 'module' }
            ),
    },
})

onMounted(async () => {
    await initServices({
        serviceConfig: {
            debugLogging: true,
        },
        caller: 'editor-' + tabsStore.activeTabIndex,
    })

    if (editorContainer.value) {
        editor = monaco.editor.create(editorContainer.value, {
            readOnly: props.readonly,
            fontSize: settingsStore.settings.editor.fontSize,
            minimap: {
                enabled: false,
            },
            wordWrap: settingsStore.settings.editor.wordWrap,
            theme: settingsStore.settings.theme,
            stickyScroll: {
                enabled: false,
            },
            automaticLayout: true,
            // glyphMargin: false,
            // fontLigatures: true,
            // scrollBeyondLastLine: false,
            // lightbulb: { enabled: false },
            wordBasedSuggestions: 'off',
        })

        let editorModel = monaco.editor.createModel(
            props.value,
            'php',
            vscode.Uri.file(
                `${props.path}/${tab.value.name}-${props.readonly ? 'readonly' : 'editable'}.php`
            )
        )

        editor.setModel(editorModel)

        editor.onDidChangeModelContent(() => {
            emit('update:value', editor.getValue())
        })

        if (!props.readonly) {
            await createWebSocketClient('ws://127.0.0.1:8080')
        }
    }
})
```

and the outcome:

![CleanShot 2024-07-15 at 18 16 33](https://github.com/user-attachments/assets/35e85f27-ae7b-4525-99a9-455946e0b726)

**Comment by kaisalmen** [comment] 2024-08-08 07:46
@saeedvaziry btw, you can get the editor or the diffeEditor from the wrapper whenever you want (e.g. re-configure it):  https://github.com/TypeFox/monaco-languageclient/blob/main/packages/wrapper/src/wrapper.ts#L132-L138

Regarding your second question. Have you loaded any syntax highlighting instructions? You can use these packages: `@codingame/monaco-vscode-standalone-language` (monarch) or `@codingame/monaco-vscode-php-default-extension` (textmate)

**Comment by saeedvaziry** [comment] 2024-12-25 19:17
Sorry @kaisalmen for this long delay.

So I handled the issue by downgrading to older version! to release the [app](https://github.com/tweakphp/tweakphp)

Now that I decided to update the packages to the latest version I faced the issue again and this time I read your replies carefully :)) especially this one

>import getConfigurationServiceOverride from '@codingame/monaco-vscode-configuration-service-override';

ended up now with this:

```
  import getConfigurationServiceOverride from '@codingame/monaco-vscode-configuration-service-override'
  import { initServices } from 'monaco-languageclient/vscode/services'

await initServices(
      {
        serviceOverrides: getConfigurationServiceOverride(),
      },
      {}
    )
```

and seems to be working fine!
