### ISSUE TITLE
Disposing last opened wrapper disables/kills language client(s) of other wrapper(s)

### ISSUE THREAD

**Issue by nametable** [TypeFox/monaco-languageclient#782] opened 2024-11-13 16:31 UTC
**Description**
When multiple separate `monaco-editor-wrapper` are loaded, with separate language server workers, disposing the last started `monaco-editor-wrapper` instance breaks the other instances.

**Steps to Reproduce**
I've built a simple reproduction app at https://github.com/nametable/monaco-editor-wrapper-languageclient-dies-repro

1. Clone the repo: `git clone https://github.com/nametable/monaco-editor-wrapper-languageclient-dies-repro`
2. Install deps and run: `yarn && yarn dev`
3. Click the "load" button for "test.js" and "test2.js" ("javascript" and "javascript2" are being used as language ids)
4. Notice that Code Actions are available in both opened editors (using Ctrl + ".")
5. Click the "kill" button for "test2.js"
6. Notice that Code Actions no longer work in the remaining editor for "test.js"

**Other Notes**
 - If you start 3 monaco-editor-wrappers, and close the one opened 2nd (or 1st), the other editors remain working.
 - If you open another editor after editor(s) break, all of the editors that were broken work again.

**Versions**
```
    "monaco-editor-wrapper": "^6.0.0-next.7",
    "monaco-languageclient": "^9.0.0-next.7",
    "vscode-languageserver": "^9.0.1"
```

**Conclusion**
I suspect either misconfiguration on my end, or that there is a bug in `monaco-editor-wrapper`. Any insights would be appreciated!

**Comment by kaisalmen** [comment] 2024-11-13 18:39
Hi @nametable this sounds like it is a bug. Thank you for providing the reproduction app.

**Comment by Zannith** [comment] 2024-11-13 19:02
I have run into the same issue, It seems to occur on all versions after [4.2.1](https://www.npmjs.com/package/monaco-editor-wrapper/v/4.2.1?activeTab=versions). But I needed to upgrade to fix some other bugs.

**Comment by kaisalmen** [comment] 2024-11-14 11:59
@nametable I have understood the problem. Your reproduction app was very useful. The answer is not straightforward, though.

In case of multiple editors and multiple language clients there is a mechanism missing that allows controlling /setting the language clients independently of the wrappers / editors. Because for monaco-editor the file extension builds the link for who is responsible. You create three servers for different artificial languages (languageIds), but the file ext is always `.js`. Once you killed one editor, the internal wiring of monaco-somehow breaks .It must have something to do with monaco's global context. When you restart an editor this internally fixed. I stumbled over this when I did not dispose the language client when the editor is disposed. If all editors use something like `extensions: [{initialExtId]` the problem is gone.

We need to provide a mechanism that allows to control the language outside a specific editor context. In your example there is actually only one language client needed, because you only edit files with same extension.

I hope this answer makes sense. I will come back with a PR.

**Comment by nametable** [comment] 2024-11-14 14:38
@kaisalmen I think your answer partially makes sense, although I still don't understand why the breakage only occurs when you close the last loaded editor. See that if you open 3 editors and then close the 1st, the 2nd and 3rd editors are not broken. Do you know why that might be?

I see and understand what you mean by `extensions: [initialExtId]` though, that seems to be a reasonable workaround at the moment (as long as I specify `enforceLanguageId: languageId`) since the independent extensions do seem to prevent breakage.

**Comment by kaisalmen** [comment] 2024-11-14 15:45
> See that if you open 3 editors and then close the 1st, the 2nd and 3rd editors are not broken. Do you know why that might be?

Not really. Something internally in monaco-editor. It must have something to do with initial order of starting the editors / language clients.

**Comment by kaisalmen** [comment] 2024-11-14 22:01
@nametable here is the WIP PR: https://github.com/TypeFox/monaco-languageclient/pull/784
It allows to init the vscode api and run language clients independent of wrapper lifecycle.

**Comment by kaisalmen** [comment] 2024-11-22 13:27
@nametable pre-releases `-next.9` are available. It took a bit longer, because the change made me realize some inconsistencies in the configuration and how it is generally applied. 

The following [example](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/multi/twoLanguageClients.ts) can now be started with or without external language clients.

**Comment by kaisalmen** [comment] 2024-12-19 10:09
Latest stable release is now available. I will close this issue now.

**Closed by kaisalmen** 2024-12-19 10:09 UTC
