### ISSUE TITLE
Fix triggering code action from the horizontal ruler

### ISSUE THREAD

**Issue by rcjsuen** [TypeFox/monaco-languageclient#11] opened 2017-07-23 06:00 UTC
Am I correct that `textDocument/codeActions` requests aren't happening? I'm guessing this is a Monaco problem or...?

**Comment by rcjsuen** [comment] 2017-07-23 11:21
Looks like the [marker in converter.ts](https://github.com/TypeFox/monaco-languageclient/blob/8fad2e2bc7e34e687cd010680cef4fc99cead3a2/src/converter.ts#L175-L179) has `null` for its `code` property so my language server isn't working. The diagnostics that was originally sent does have a code and it seems to be [converted correctly](https://github.com/TypeFox/monaco-languageclient/blob/8fad2e2bc7e34e687cd010680cef4fc99cead3a2/src/converter.ts#L516-L527) so I'm not sure why the code later disappears.

**Comment by rcjsuen** [comment] 2017-07-23 12:05
I opened Microsoft/vscode#31275 which explains why the `code` property is being set to `null`.

However, I still can't figure out where my code actions are for diagnostics that have a non-zero code.

**Comment by akosyakov** [comment] 2017-07-24 03:54
Do you have `glyphMargin` set to true?

**Comment by rcjsuen** [comment] 2017-07-24 07:36
@akosyakov Thanks for the tip! Setting it to `true` got the light bulb to show up. Unfortunately, clicking the light bulb doesn't do anything... :(

My language server works in VS Code and Eclipse LSP4E so I think I've implemented the protocol correctly...

**Comment by akosyakov** [comment] 2017-07-24 07:41
@svenefftinge maybe you know what can be missing on Monaco-side.

**Comment by akosyakov** [comment] 2017-07-24 09:42
@rcjsuen could be closed?

**Comment by rcjsuen** [comment] 2017-07-24 09:45
@akosyakov Not yet because clicking the light bulb doesn't do anything. :(

**Comment by svenefftinge** [comment] 2017-07-27 07:25
Have you registered the commands that are sent through the CodeActions?
Clicking the bulb or pressing (<kbd>CMD</kbd> + <kbd>.</kbd>) should trigger the `IContextMenuService` with the appropriate commands.

**Comment by rcjsuen** [comment] 2017-07-27 10:05
> Have you registered the commands that are sent through the CodeActions?

No. My language server works in VS Code without me having to explicitly register so I didn't think I had to do anything.

Using the keybinding you suggested got a menu to popup with my command. It doesn't run because of #12 but at least the menu shows up anyway.

**Comment by akosyakov** [comment] 2017-08-29 07:40
After https://github.com/TypeFox/monaco-languageclient/pull/21 gets merged there will be a light build for the code action in the example project.

When one clicks on it nothing happens then the code action is expected which converts the whole document to the uppercase.
Triggering the code actoin with keyboard (<kbd>CMD</kbd> + <kbd>.</kbd>) works though.

**Comment by akosyakov** [comment] 2017-08-29 07:41
@rcjsuen if you are interested feel free to investigate it. I've sent your invitation with the write access that you can open the PR in this repo instead of the fork.

**Comment by akosyakov** [comment] 2017-08-30 04:56
It is still the issue, see https://github.com/TypeFox/monaco-languageclient/issues/11#issuecomment-325581448

**Comment by rcjsuen** [comment] 2017-08-30 05:38
If you step through the code you will see that [the menu does get shown](https://github.com/Microsoft/vscode/blob/aca01f2daab4b038c809e81494cba14a1970f7f6/src/vs/platform/contextview/browser/contextMenuHandler.ts#L88-L112). However, it then [becomes hidden](https://github.com/Microsoft/vscode/blob/aca01f2daab4b038c809e81494cba14a1970f7f6/src/vs/platform/contextview/browser/contextMenuHandler.ts#L127-L142) when the `onMouseDown` gets processed.

**Comment by akosyakov** [comment] 2017-08-30 05:54
I wonder whether it is reproducible without `monaco-languageclient` with the latest version of the Monaco editor. If it is we need to open an issue for monaco itself.

**Comment by rcjsuen** [comment] 2017-08-30 08:39
I (think I) wiped everything related to `monaco-languageclient` from the `example/` folder and was still able to reproduce the problem just by manually [registering a CodeActionProvider](https://github.com/Microsoft/monaco-editor/blob/v0.9.0/monaco.d.ts#L4010) on Monaco 0.9.0.

**Comment by akosyakov** [comment] 2017-08-30 09:08
@rcjsuen looks like a bug in Monaco then, I usually try to reproduce it the [playground](https://microsoft.github.io/monaco-editor/playground.html) and post a bug with the code snippet here: https://github.com/Microsoft/monaco-editor/issues

**Comment by rcjsuen** [comment] 2017-08-30 09:37
Thanks for the pointer, @akosyakov. I totally forgot about the Monaco Editor Playground.

I've opened [Microsoft/monaco-editor#574](https://github.com/Microsoft/monaco-editor/issues/574).

**Closed** 2018-03-17 07:27 UTC
Labels: bug, help wanted, question
