### ISSUE TITLE
extension moduel getLocalExtHostExtensionService blocked

### ISSUE THREAD

**Issue by coyzeng** [TypeFox/monaco-languageclient#541] opened 2023-09-21 10:19 UTC

**Comment by kaisalmen** [comment] 2023-09-25 09:31
@coyzeng Please take your time to describe your problem properly.

**Comment by OliverwengFiltered** [comment] 2023-10-05 14:29
I'm having the same issue after upgrading the monaco-languageclient to v6.5.1

did some debugging with break points on the front end. It looks like the getLocalExtHostExtensionService call promise never successfully resolve so the code doesn't hit line 39.

any insights? @kaisalmen 

<img width="1230" alt="Screenshot 2023-10-05 at 10 25 20 AM" src="https://github.com/TypeFox/monaco-languageclient/assets/28814939/35a50251-c302-4695-97d6-f4dfe67859c2">

**Comment by kaisalmen** [comment] 2023-10-05 16:40
@CGNonofr do you have an idea?
@OliverwengFiltered can you reproduce this with our local webpack verification example?

**Comment by CGNonofr** [comment] 2023-10-05 16:47
Was `initializeExtensions` called?

**Comment by kaisalmen** [comment] 2023-10-05 17:53
This should ensure it:
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/client/src/monaco-vscode-api-services.ts#L27-L41
It is called at line 32.

**Comment by OliverwengFiltered** [comment] 2023-10-05 18:46
was doing some debugging, the code I was showing is inside the `initializeExtensions` call.

<img width="970" alt="Screenshot 2023-10-05 at 2 43 35 PM" src="https://github.com/TypeFox/monaco-languageclient/assets/28814939/22918f27-04ea-4017-b5af-ee4d692e4bcf">

the above initialize function is [this](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/client/src/monaco-vscode-api-services.ts#L27-L41) function as @kaisalmen  pointed out, it's the bundled version.

and then I stepped into it, got the below image, and it stuck at the highlighted line and never got to the next line.

<img width="1043" alt="Screenshot 2023-10-05 at 2 44 03 PM" src="https://github.com/TypeFox/monaco-languageclient/assets/28814939/524de94c-a39a-408a-8b7b-a421f2dea8f2">

**Comment by samirzubi-db** [comment] 2023-10-06 15:19
I am having the same issue as above where getLocalExtHostExtensionService promise does not resolve or reject.

**Comment by samirzubi-db** [comment] 2023-10-06 16:56
@kaisalmen thanks for the quick response I am not using `@codingame/monaco-vscode-theme-defaults-default-extension`. I am only calling `initialize` from `vscode/services` and then the `initialize` from `vscode/extensions`. I am not using any service overrides since I need only the default ones.

**Comment by kaisalmen** [comment] 2023-10-06 17:51
@samirzubi-db or @OliverwengFiltered can you publish a reproducible example / repo somewhere. I can't reproduce what you see. I assume you cannot reproduce this with the examples from this repo or can you?

**Comment by coyzeng** [comment] 2023-10-10 08:47
> @samirzubi-db or @OliverwengFiltered can you publish a reproducible example / repo somewhere? I can't reproduce what you see. I assume you cannot reproduce this with the examples from this repo or can you?

https://github.com/coyzeng/monaco-example.git

![image](https://github.com/TypeFox/monaco-languageclient/assets/15525280/f4a6b352-f097-4970-a3c9-137ea069c97f)

**Comment by coyzeng** [comment] 2023-10-10 08:51
![image](https://github.com/TypeFox/monaco-languageclient/assets/15525280/0000c5d6-22c1-4816-8ac5-a1ca473337ed)

**Comment by kaisalmen** [comment] 2023-10-10 09:50
@coyzeng @OliverwengFiltered @CGNonofr thank you, whatever react does provokes the issue. I don't know why, yet.

When I move the init code to your main and comment the react usage the init works as expected:
```js
const initMlc = async () => {
    await initServices({
        debugLogging: true
    });
};
console.log(0)
initMlc();
console.log(1)

// const root = ReactDOM.createRoot(document.getElementById('root')!);
// root.render(<SQLEditor/>);
```
Can it be that using `useEffect` provokes the problem?

**Comment by CGNonofr** [comment] 2023-10-10 09:58
Wasn't it called too late? (after the editor creation/default services instantiation)

**Comment by kaisalmen** [comment] 2023-10-10 10:02
Is it Monday again?! I don't see a fundamental difference in our react example.

**Comment by kaisalmen** [comment] 2023-10-10 10:24
The actual problem is not react, but defining `monaco.editor.defineTheme` directly in an import file (`@github`). If wrap that in an exported function and call it at a proper place. Everything works.

**Comment by kaisalmen** [comment] 2023-10-10 10:25
Sorry, closed this to quickly. @OliverwengFiltered should verify/comment if it is the same issue.

**Comment by samirzubi-db** [comment] 2023-10-10 11:15
I had the same issue with the theme being declared directly. Thank you for looking into this @kaisalmen and @coyzeng for the repro!

**Comment by CGNonofr** [comment] 2023-10-10 12:17
I'll add a check in the monaco-vscode-api service initialization to make sure the services aren't already initialized to prevent such confusing issues

**Comment by kaisalmen** [comment] 2023-10-10 15:52
> well, that did not solve my issue on my end. I will put together a sample project to reproduce in a few hours.

Thank you.

**Comment by OliverwengFiltered** [comment] 2023-10-11 16:17
Hi @kaisalmen  and @CGNonofr 

I have uploaded a public repo to reproduce the issue: https://github.com/OliverwengFiltered/monaco-test

simply follow the below steps to reproduce.
1. clone the repo.
2. npm install.
3. npx webpack build
4. npm start.
5. visit localhost:3000
6. the editor should load.
7. now go to monacoInit.js and uncomment those lines.
8. now start server again, you will see a blank state.

curious why calling `Editor.getModels()` will prevent the editor from being rendered with latest version. (same code is not painting blank state with monaco-languageclient v6.4.6)

**Comment by OliverwengFiltered** [comment] 2023-10-11 16:20
@CGNonofr  ok, so which api method should I use to check if it has been initialized or not ?

**Comment by OliverwengFiltered** [comment] 2023-10-11 16:40
so in this case, @CGNonofr 
if I have to do dispose() before editor's creation. any recommendations?
it seems currently, the `Editor.getModels()` and `LanguageClientLib.initServices()` are both initialize monaco services, and they can't co-exists in the new 6.5.2 version. And the check `wasVscodeApiInitialized()` returns false even if `Editor.getModels()` are called before hand.


<img width="936" alt="Screenshot 2023-10-11 at 12 37 05 PM" src="https://github.com/TypeFox/monaco-languageclient/assets/28814939/74060d8a-6eae-4279-a8b1-19db0b31b874">

**Comment by OliverwengFiltered** [comment] 2023-10-11 17:35
that makes sense, @CGNonofr .

and I can verify that calling LanguageClientLib.initServes() function before the `.getModels` function works.

Thanks, we can close this ticket now.

Thanks all.

**Comment by kaisalmen** [comment] 2023-10-11 17:44
Wonderful. 🎉

**Closed by kaisalmen** 2023-10-11 17:44 UTC
