### ISSUE TITLE
Quick fix is not available when changing message in middleware.

### ISSUE THREAD

**Issue by CherryPetale** [TypeFox/monaco-languageclient#588] opened 2024-01-04 16:47 UTC
Quick fix is not available when changing message in middleware.

```diff
return new MonacoLanguageClient({
    name: 'client name',
    clientOptions: {
       ...
        middleware: {
            handleDiagnostics: (uri, d, next) => {
                const newd = d.map((v) => {
                    if (v.message.includes("fix available")) {
+                        v.message = "change message";
                    }
                    return v;
                });
                next(uri, newd);
            }
        }
    }
});
```

<img width="488" alt="screenshot 2024-01-05 013739" src="https://github.com/TypeFox/monaco-languageclient/assets/29115753/2881b8c0-9859-44bb-9b0f-323282f7cb24">

<img width="359" alt="screenshot 2024-01-05 013632" src="https://github.com/TypeFox/monaco-languageclient/assets/29115753/4df5fcd1-c27f-4cfe-adf1-82d3e2655ff7">

or is it a monaco-editor issue?

**Comment by msujew** [comment] 2024-01-04 17:01
@CherryPetale Does this work as expected in vscode? I don't think this should work, since the code actions/quick fixes are attached to the diagnostic. If the diagnostic changes somehow in transition, it is expected that the editor cannot attach the code actions anymore, since the diagnostic they were attached to no longer exists (at least in the expected form).

**Comment by CherryPetale** [comment] 2024-01-04 17:44
@msujew I don't know how to check with vscode so I can't try right away, but all I am trying to do is translate and display the error text, so if it is too difficult I will give up.

**Comment by kaisalmen** [comment] 2024-03-13 13:08
@CherryPetale did succeed with reproducing it in VSCode?

**Comment by CherryPetale** [comment] 2024-03-13 16:26
@kaisalmen Sorry. I didn't know how to do it and gave up. Also, I am going to close issue if there are no problems, as it does not seem to be the original use of the middleware in the first place.

**Comment by kaisalmen** [comment] 2024-03-22 13:20
@CherryPetale I will close this now. Feel free to open another issue or discussion if it makes sense.

**Closed by kaisalmen** 2024-03-22 13:20 UTC
